name: CI/CD

on:
  push:
    branches: [ master ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Build
      run: npm run build

    - name: curl
      run: curl https://google.com
